// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAuSPooYSBYfFgqnMdqjzTSAwJI-rhstKA',
    appId: '1:305501914796:web:d829ea8e03bdc8338c0109',
    messagingSenderId: '305501914796',
    projectId: 'overturescoutingsuite',
    authDomain: 'overturescoutingsuite.firebaseapp.com',
    databaseURL: 'https://overturescoutingsuite-default-rtdb.firebaseio.com',
    storageBucket: 'overturescoutingsuite.firebasestorage.app',
    measurementId: 'G-2M42DD53M7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCtIUDgd18X3A2uEkuO-QbvOt2o2Wvyo6c',
    appId: '1:305501914796:android:dba62c6480e2bbb68c0109',
    messagingSenderId: '305501914796',
    projectId: 'overturescoutingsuite',
    databaseURL: 'https://overturescoutingsuite-default-rtdb.firebaseio.com',
    storageBucket: 'overturescoutingsuite.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAuSPooYSBYfFgqnMdqjzTSAwJI-rhstKA',
    appId: '1:305501914796:web:a0a977170d8f42de8c0109',
    messagingSenderId: '305501914796',
    projectId: 'overturescoutingsuite',
    authDomain: 'overturescoutingsuite.firebaseapp.com',
    databaseURL: 'https://overturescoutingsuite-default-rtdb.firebaseio.com',
    storageBucket: 'overturescoutingsuite.firebasestorage.app',
    measurementId: 'G-LCH586B3HM',
  );
}
